### PR TITLE
feat: add brightness slider

### LINKED ISSUE #4: Brightness Slider
Hi,
Works perfectly, but
Where is the Brightness Slider? :D
Do you plan to add that?

### PR DESCRIPTION
**Pull request by tnc1997**
Closes #4

### CODE REVIEW

**Comment by tnc1997** [comment]
Hi @thewh1teagle, thank you for your work on this application!

I am experiencing a few difficulties attempting to test the production build of the application due to this error:

> thread 'tokio-runtime-worker' panicked at rust/src-tauri/src/controller.rs:94:14:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: happy::controller::Controller::set_rgb::{{closure}}
   5: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   6: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   7: tauri::ipc::InvokeResolver<R>::respond_async_serialized::{{closure}}
   8: tokio::runtime::task::core::Core<T,S>::poll
   9: tokio::runtime::task::harness::Harness<T,S>::poll
  10: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  11: tokio::runtime::scheduler::multi_thread::worker::Context::run
  12: tokio::runtime::context::runtime::enter_runtime
  13: tokio::runtime::scheduler::multi_thread::worker::run
  14: tokio::runtime::task::core::Core<T,S>::poll
  15: tokio::runtime::task::harness::Harness<T,S>::poll
  16: tokio::runtime::blocking::pool::Inner::run

EDIT: Please accept my apologies I realise now that this was likely being caused by the device not being set 😳

**Comment by thewh1teagle** [comment]
Hey!

Thanks for your work on this. I tested it and found an issue with the PR. The color state isn't persistent when using the brightness slider. It always changes to green when adjusting the brightness, instead of maintaining the selected color.

**Comment by tnc1997** [comment]
No worries, you're welcome! Thanks for giving these changes a test. I might have misunderstood as I was (maybe wrongly) basing these changes on the set intensity logic [here](https://gitlab.com/madhead/saberlight/-/blob/master/protocols/Triones/protocol.md#white-color).

**Comment by cjwomack** [comment]
Just a random comment. Maybe try converting the RGB color to HSL and then modifying the lightness value? When I get time to play around with the code to compile a 32 bit windows version and/or a 32 bit linux version (I have an Intel PC stick and some old netbooks), I might give this a go.

**Comment by tnc1997** [comment]
Hi @thewh1teagle, I was just wondering if you might be able to review my amendments to change the brightness of the picked colour, instead of resetting the colour to white?

**Comment by thewh1teagle** [comment]
@tnc1997 

I tested it just now on macOS. 
It works great!

I'll merge and release new version that include it. 
Thanks for your contribution!

**Comment by thewh1teagle** [comment]
Released to 1.0.5

**Pull request merged**
